# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  postgresql:
    image: postgres:alpine3.16
    container_name: postgresql
    hostname: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"


volumes:
  postgresql-data:
    name: postgresql-data
